version: '3.8'

services:
  client:
    build: .
    container_name: quantiplant-client
    environment:
      - SERVER_URL=http://192.168.1.100:5001
      - DEVICE_ID=rpi-1
    restart: unless-stopped
