version: '3.8'

services:
  server:
    build:
      context: ./server
    container_name: quantiplant-server
    ports:
      - "5001:5001"
    volumes:
      - ./server/uploads:/app/uploads
    restart: unless-stopped
