version: '3.8'

services:
  server:
    build:
      context: .
    container_name: quantiplant-server
    ports:
      - "5001:5001"
    volumes:
      - ./server/uploads:/app/uploads
      - /home/jeremy/TFG-QuantiPlant/client/toggle_usb.sh:/toggle_usb.sh:ro
    restart: unless-stopped
